name: Build and Publish
on:
  push:
    branches: [ master ]
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pipenv run pytest .
  
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          RELEASE_BRANCHES: master
          DEFAULT_BRANCH: master
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: rssiweb/website
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_names: true
        tag_semver: true
    - name: Trigger Deploy Services
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: rssiweb/services
        event-type: deploy
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

